### ISSUE TITLE
How to save or create playlist within JAKYM?

### ISSUE THREAD

**Issue by lodenrogue** [themayankjha/JAKYM#2]

**Comment by themayankjha** [comment]
hello loden, I hadn't thought of this yet. This is actually something that even I would like to use.
I will add it to the todo for the next release.

**Comment by lodenrogue** [comment]
I love the tool. I'm looking to replace most of my UI tools with command line alternatives and this has the potential to be a great replacement for Youtube Music. Let me know if you'd like to discuss some architectural approaches.

**Comment by themayankjha** [comment]
Surely, I would love to. I was thinking in the terms of a playlist.json file, where adding different playlists and songs would be very easy to read from and write into. What are your suggestions?

**Comment by lodenrogue** [comment]
Yes. I was also thinking a file. Maybe simpler than json; just a list of songs/playlists one per line. That way you may be able to extend JAKYM to be used with pipes in the future and accept a stream of songs.

**Comment by themayankjha** [comment]
The issue I think with just a text file will arise is classification.
I won't be able to list down my favourite songs in a playlist called favourite.
sorting in a JSON may let me name my playlist and import the whole playlist without much processing as JSON is quite easy to import/export

**Comment by lodenrogue** [comment]
JSON is easy for us to understand because we're used to working with it but there will be users who are not so familiar with it. What if you could accept either:

1. 1 or more files as playlists (1 file per playlist the user wants to play)
2. A stream of text (thinking of the Unix principle: Text is the universal interface)
3. A directory of playlists (1 playlist per file inside the directory)

**Comment by themayankjha** [comment]
I understand what you are thinking of by saying a text file but JSON is just a fancy text file that can be integrated without writing much code. I think from portability backing up a single file will be better JSON or not so maybe a whole directory will be a pass. I think the stream of text will be a good option you said it will be easy to pipe music directly into the program.

What do you say to a JSON file to save/read playlists to/from inside the application with also will accept a text stream for easy piping

**Comment by lodenrogue** [comment]
That's a good compromise

**Comment by themayankjha** [comment]
Alright, I will add this feature to the plans for next update.

**Comment by lodenrogue** [comment]
Any progress on this? Do you need help?

**Comment by themayankjha** [comment]
Hello, I am currently busy in exams. Thus no updates so far. I will resume working when its all done don't worry :)

**Comment by themayankjha** [comment]
So, i have added the ability to save and load playlist to and from a single file. Since i have already added support for various command line arguments, I have added one so that one can directly start music from the playlist by a single command.
This was the easy part, making piping work is quite tricky and i have tried some approaches but it didn't properly work.
I hope to finish it soon though so more updates soon :)

**Comment by themayankjha** [comment]
hello loden, I tried lot of ways to integrate piping into jakym, however piping would require me to read from standard input and parse it, this for the sake of cross platform compatability piping does not work properly, hence i have decided to not include piping support. 

since the jakym now has its way to save and create playlists along with accepting a stream of songs i hope you would understand why i would not like to spend more development time on this issue.
